---
- name: ec2-instances
  hosts: ec2
  gather_facts: false
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - name: apt-update
      apt:
        update_cache: yes
        upgrade: safe

    - name: install-packages
      apt: 
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - python3
        - python3-pip
        - docker
        - docker-compose
        - git

    - name: docker-group-users
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: docker-services
      service:
        name: docker
        state: started
        enabled: yes

    - name: clone-app-repo
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_dir }}"
        version: main

    - name: docker-build
      docker_compose:
        project_src: "{{ app_dir }}"
        state: present
        pull: yes
        build: yes
        remove_orphans: yes

    - name: dockercompose-run
      docker_compose:
        project_src: "{{ app_dir }}"
        state: present
        started: yes

    - name: test-app-status
      uri:
         url: "http://{{ ansible_host }}:8080"
         method: GET
         status_code: 200
